// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"github.com/SliverFlow/minidouyin/app/user/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReply = pb.CreateReply
	CreateReq   = pb.CreateReq

	User interface {
		// 创建用户
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 创建用户
func (m *defaultUser) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}
